name: Merge

on:
  pull_request:
    types:
      - closed 
    branches:
      - main 

jobs:
  delete_branch:
      runs-on: ubuntu-latest
      steps:
        - name: delete branch
          if: github.event.pull_request.merged == true
          uses: SvanBoxel/delete-merged-branch@main
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}