name: Merge

on:
  pull_request:
    types:
      - closed 
    branches:
      - main 

jobs:
  delete_branch:
      runs-on: ubuntu-latest
      steps:
        - name: Debug Info
          run: |
            pwd
            ls -la $GITHUB_WORKSPACE
        - name: delete branch
          if: github.event.pull_request.merged == true
          run: |
            cd $GITHUB_WORKSPACE
            git checkout ${{ github.event.pull_request.base.ref }}
            git branch -d ${{ github.event.pull_request.head.ref }}
            git push origin --delete ${{ github.event.pull_request.head.ref }}